"""E2E test: Concurrent submissions to the same bounty.

Validates: multiple contributors submit to same bounty -> first to pass wins.

Tests cover race conditions, duplicate detection, and concurrent
access patterns using both synchronous and async test clients.

Requirement: Issue #196 item 4.
"""

import asyncio

import pytest
from fastapi.testclient import TestClient
from httpx import AsyncClient

from tests.e2e.conftest import create_bounty_via_api
from tests.e2e.factories import (
    build_bounty_create_payload,
    build_submission_payload,
)


class TestConcurrentSubmissions:
    """Validate handling of multiple simultaneous submissions."""

    def test_multiple_submissions_sequentially(self, client: TestClient) -> None:
        """Verify that multiple unique submissions are all accepted.

        Each submission uses a unique PR URL generated by the factory.
        """
        bounty = create_bounty_via_api(
            client,
            build_bounty_create_payload(
                title="Concurrent submission target",
                reward_amount=1000.0,
            ),
        )
        bounty_id = bounty["id"]

        successful_submissions = []
        for i in range(5):
            payload = build_submission_payload()
            response = client.post(
                f"/api/bounties/{bounty_id}/submit",
                json=payload,
            )
            assert response.status_code == 201
            successful_submissions.append(response.json())

        # Verify all submissions recorded
        assert len(successful_submissions) == 5

        # Verify via list endpoint
        subs = client.get(f"/api/bounties/{bounty_id}/submissions").json()
        assert len(subs) == 5

    def test_first_submission_wins_on_completion(self, client: TestClient) -> None:
        """Verify that the bounty completes after submissions and payout.

        After multiple submissions, the bounty transitions to completed
        once the first qualifying submission is approved.
        """
        bounty = create_bounty_via_api(
            client,
            build_bounty_create_payload(reward_amount=750.0),
        )
        bounty_id = bounty["id"]

        # Three submissions with unique PR URLs
        for i in range(3):
            client.post(
                f"/api/bounties/{bounty_id}/submit",
                json=build_submission_payload(),
            )

        # Advance bounty through lifecycle
        client.patch(f"/api/bounties/{bounty_id}", json={"status": "in_progress"})
        client.patch(f"/api/bounties/{bounty_id}", json={"status": "completed"})
        client.patch(f"/api/bounties/{bounty_id}", json={"status": "paid"})

        # Verify final state
        final = client.get(f"/api/bounties/{bounty_id}").json()
        assert final["status"] == "paid"
        assert final["submission_count"] == 3


class TestDuplicateSubmissionPrevention:
    """Validate that duplicate PR URLs are rejected."""

    def test_duplicate_pr_url_rejected(self, client: TestClient) -> None:
        """Verify that submitting the same PR URL twice is rejected.

        The bounty service checks for duplicate ``pr_url`` values on the
        same bounty and returns a 400 error for duplicates.
        """
        bounty = create_bounty_via_api(
            client,
            build_bounty_create_payload(),
        )
        bounty_id = bounty["id"]

        duplicate_url = "https://github.com/SolFoundry/solfoundry/pull/999"
        first_payload = build_submission_payload(pr_url=duplicate_url)
        second_payload = build_submission_payload(pr_url=duplicate_url)

        # First submission succeeds
        first_response = client.post(
            f"/api/bounties/{bounty_id}/submit",
            json=first_payload,
        )
        assert first_response.status_code == 201

        # Duplicate PR URL rejected
        second_response = client.post(
            f"/api/bounties/{bounty_id}/submit",
            json=second_payload,
        )
        assert second_response.status_code == 400
        assert "already been submitted" in second_response.json()["detail"]

    def test_different_pr_urls_allowed(self, client: TestClient) -> None:
        """Verify different PR URLs are accepted for the same bounty.

        Each unique PR URL should be accepted regardless of who submits.
        """
        bounty = create_bounty_via_api(
            client,
            build_bounty_create_payload(),
        )
        bounty_id = bounty["id"]

        for i in range(3):
            payload = build_submission_payload(
                pr_url=f"https://github.com/SolFoundry/solfoundry/pull/{100 + i}",
            )
            response = client.post(
                f"/api/bounties/{bounty_id}/submit",
                json=payload,
            )
            assert response.status_code == 201

        subs = client.get(f"/api/bounties/{bounty_id}/submissions").json()
        assert len(subs) == 3


class TestConcurrentAsyncSubmissions:
    """Validate concurrent submissions using async HTTP client."""

    @pytest.mark.asyncio
    async def test_concurrent_submissions_via_async_client(
        self, async_client: AsyncClient
    ) -> None:
        """Verify concurrent async submissions are all recorded.

        Uses ``asyncio.gather`` to submit 10 solutions simultaneously,
        simulating real-world concurrent contributor activity.
        """
        # Create bounty
        create_response = await async_client.post(
            "/api/bounties",
            json=build_bounty_create_payload(
                title="Async concurrent test",
                reward_amount=500.0,
            ),
        )
        assert create_response.status_code == 201
        bounty_id = create_response.json()["id"]

        # Submit 10 solutions concurrently with unique PR URLs
        async def submit_solution(contributor_index: int) -> int:
            """Submit a solution and return the HTTP status code.

            Args:
                contributor_index: Unique index for this contributor.

            Returns:
                The HTTP response status code.
            """
            payload = {
                "pr_url": f"https://github.com/SolFoundry/solfoundry/pull/{200 + contributor_index}",
                "submitted_by": f"async-contributor-{contributor_index}",
                "notes": f"Concurrent submission #{contributor_index}",
            }
            response = await async_client.post(
                f"/api/bounties/{bounty_id}/submit",
                json=payload,
            )
            return response.status_code

        results = await asyncio.gather(*(submit_solution(i) for i in range(10)))

        # All should succeed (unique PR URLs)
        assert all(status == 201 for status in results)

        # Verify total count
        subs_response = await async_client.get(f"/api/bounties/{bounty_id}/submissions")
        assert subs_response.status_code == 200
        subs = subs_response.json()
        assert len(subs) == 10

    @pytest.mark.asyncio
    async def test_concurrent_duplicate_detection(
        self, async_client: AsyncClient
    ) -> None:
        """Verify duplicate detection under concurrent submission load.

        When multiple requests try to submit the same PR URL
        concurrently, only one should succeed.
        """
        create_response = await async_client.post(
            "/api/bounties",
            json=build_bounty_create_payload(),
        )
        bounty_id = create_response.json()["id"]

        shared_url = "https://github.com/SolFoundry/solfoundry/pull/duplicate-race"

        async def submit_duplicate(index: int) -> int:
            """Attempt to submit the shared PR URL.

            Args:
                index: Submitter index for unique ``submitted_by``.

            Returns:
                The HTTP response status code.
            """
            payload = {
                "pr_url": shared_url,
                "submitted_by": f"racer-{index}",
                "notes": "Racing submission",
            }
            response = await async_client.post(
                f"/api/bounties/{bounty_id}/submit",
                json=payload,
            )
            return response.status_code

        results = await asyncio.gather(*(submit_duplicate(i) for i in range(5)))

        # At least one should succeed, the rest should fail
        successes = sum(1 for r in results if r == 201)
        failures = sum(1 for r in results if r == 400)
        assert successes >= 1, "At least one submission should succeed"
        assert successes + failures == 5


class TestSubmissionToCompletedBounty:
    """Validate that completed/paid bounties reject new submissions."""

    def test_cannot_submit_to_completed_bounty(self, client: TestClient) -> None:
        """Verify that submissions are rejected for completed bounties.

        Once a bounty reaches ``completed`` status, no new submissions
        should be accepted.
        """
        bounty = create_bounty_via_api(
            client,
            build_bounty_create_payload(),
        )
        bounty_id = bounty["id"]

        # Advance to completed
        client.patch(f"/api/bounties/{bounty_id}", json={"status": "in_progress"})
        client.patch(f"/api/bounties/{bounty_id}", json={"status": "completed"})

        # Try to submit -- should fail
        response = client.post(
            f"/api/bounties/{bounty_id}/submit",
            json=build_submission_payload(),
        )
        assert response.status_code == 400
        assert "not accepting submissions" in response.json()["detail"]

    def test_cannot_submit_to_paid_bounty(self, client: TestClient) -> None:
        """Verify that submissions are rejected for paid bounties.

        The ``paid`` status is terminal -- no further activity is allowed.
        """
        bounty = create_bounty_via_api(
            client,
            build_bounty_create_payload(),
        )
        bounty_id = bounty["id"]

        # Advance to paid
        client.patch(f"/api/bounties/{bounty_id}", json={"status": "in_progress"})
        client.patch(f"/api/bounties/{bounty_id}", json={"status": "completed"})
        client.patch(f"/api/bounties/{bounty_id}", json={"status": "paid"})

        # Try to submit -- should fail
        response = client.post(
            f"/api/bounties/{bounty_id}/submit",
            json=build_submission_payload(),
        )
        assert response.status_code == 400
